/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FlutterAppIcons {
  FlutterAppIcons._();

  static const _kFontFam = 'MyFlutterApp';
  static const _kFontPkg = null;

  static const IconData edit =
  IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download =
  IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload =
  IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asterisk =
  IconData(0xf069, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData address_card =
  IconData(0xf2bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
